<?php

$start = microtime(true);

header("Cache-Control: no-cache, must-revalidate",true);

if(isset($_REQUEST['source']))
{
  show_source('index.php');
  exit(0);
}

////////////////////////////////////////////////////////
// Configuration starts here
$services = array('bfgminer', 'cgminer', 'cpuminer');
$out_dir = '/run/shm/';
$log_file = $out_dir.'crutch.log';
$timestamp_format = '\o\n F j, Y \a\t G:i:s T';
// Configuration ends here
////////////////////////////////////////////////////////

?>
<html>
<head>
    <title>Rouben's non-pretty miner status</title>
</head>
<h2>This is a non-pretty miner status page... it is rather bland, but it is 100% IE compatible! ;)</h2>
<h3>Other stuff on the menu</h3>
<ul>
  <li><a href="?source">Show me the code!</a>
  <li><a href="miner.php">BFGMiner/CGMiner dashboard</a>
</ul>

<?php
foreach ($services as $service)
{
  $status_file = $out_dir.$service.".status";
  echo "<h3>Screenshot of ".$service;
  if (is_readable($status_file))
  {
    echo " was taken ".date($timestamp_format, filemtime($status_file))."</h3>\n";
    echo "<textarea rows=25 cols=80 readonly>".file_get_contents($status_file)."</textarea>\n";
  }
  else
  {
    echo " is not available!</h3>";
    echo "Screenshot file ".$status_file." is not readable!\n";
  }
}
?>

<h3>CrutchLog
<?php
if (is_readable($log_file))
{
  echo " was last modified ".date($timestamp_format, filemtime($log_file))."</h3>\n";
  echo "<textarea rows=25 cols=80 readonly>\n";
  echo file_get_contents($log_file);
  echo "</textarea>\n";
}
else
{
  echo " is not available!</h3>";
  echo "Log file ".$log_file." is not readable!\n";
}
?>
<hr>
System uptime: <?php echo exec("uptime"); ?>
<br />
This page was generated by a <a href="http://beagleboard.org/Products/BeagleBone%20Black" target="_blank"><img src="boristux_w_logo.png" border=0 alt="BeagleBoard.org BeagleBone Black"></a> powered by a <img src="sitara_arm_processors.png" border=0 alt="Sitara ARM Processors">
<?php
$end = microtime(true);
$creationtime = ($end - $start);
printf(" in %.6f seconds", $creationtime);
echo " ".date($timestamp_format).".\n\n";
?>
